config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount Rapidfire::Engine => "/rapidfire"
  root 'home_page#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def can_administer?
    current_user.try(:admin?)
  end
end

app/controllers/home_page_controller.rb
class HomePageController < ApplicationController
  def index
  end
end

app/controllers/rapidfire/answer_groups_controller.rb
module Rapidfire
  class AnswerGroupsController < Rapidfire::ApplicationController
    before_filter :find_question_group!

    def new
      @answer_group_builder = AnswerGroupBuilder.new(answer_group_params)
    end

    def create
      @answer_group_builder = AnswerGroupBuilder.new(answer_group_params)

      if @answer_group_builder.save
        redirect_to question_groups_path

        SurveyAttemptedJob
          .perform_later(@answer_group_builder.question_group)
      else
        render :new
      end
    end

    private
    def find_question_group!
      @question_group = QuestionGroup.find(params[:question_group_id])
    end

    def answer_group_params
      answer_params = { params: (params[:answer_group] || {}) }
      answer_params.merge(user: current_user, question_group: @question_group)
    end
  end
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/views/home_page/index.html.erb
<div class="text-center py-20">
  Welcome to rapidfire. Try rapidfire surveys <%= link_to "here", rapidfire_path %>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="text-center">Built with love by Codemancers</div>
</footer>

app/views/layouts/_navigation.html.erb
<nav class="flex items-center justify-between p-4">
  <a href="/" class="inline-block">Rapidfire</a>
  <div class="flex gap-6 items-center">
    <% if user_signed_in? %>
      <%= link_to('Logout', '/users/sign_out', method: :delete) %>
    <% else %>
      <%= link_to('Login', '/users/sign_in') %>
    <% end %>
    <%= link_to('Github', 'https://github.com/code-mancers/rapidfire') %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rapidfire App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'layouts/navigation'%>

    <% if alert %>
      <%= alert %>
    <% end %>
    <% if notice %>
       <%= notice %>
    <% end %>

    <div class="p-4">
      <%= yield %>
    </div>

    <%= render 'layouts/footer'%>
  </body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title RapidfireDemo
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body
    = render partial: "shared/header"

    .container
      .row
        .col-md-12
          = yield

    %br
    %br
    %br
    %br
    %br
    = render partial: "shared/footer"
    - if Rails.env.production?
      = render partial: "shared/google_analytics"

app/views/rapidfire/answers/_checkbox.html.erb
<%= render partial: "rapidfire/answers/errors", locals: {answer: answer} %>

<div class="form-group">
<%= f.label :answer_text, answer.question.question_text, class: "title is-6" %>
<br>
<%= f.fields_for :answer_text do |af| %>
  <%- answer.question.options.each_with_index do |option, index| %>
    <%= af.label index, class: "checkbox full-width" do %>
      <%= af.check_box index, { checked: checkbox_checked?(answer, option) }, option %>
      <%= option %>
    <% end %>
  <% end %>
<% end %>
</div>

app/views/rapidfire/answers/_date.html.erb
<%= render partial: "rapidfire/answers/errors", locals: {answer: answer} %>
<div class="form-group">
<%= f.label :answer_text, answer.question.question_text, class: "title is-6" %>
<%= f.text_field :answer_text, placeholder: answer.question.placeholder, class: "input" %>
</div>

app/views/rapidfire/answers/_errors.html.erb
<%- if answer.errors.any? %>
  <div class="message is-danger">
    <ul class="message-body">
      <%- answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/rapidfire/answers/_file.html.erb
<div>
  <%= f.label :answer_text, answer.question.question_text, class: "block text-sm font-medium leading-6 text-gray-900" %>
  <%= f.file_field :file, class: "block w-full p-1 mt-2 rounded-md border-0 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 sm:text-sm sm:leading-6" %>
  <%= render partial: "rapidfire/answers/errors", locals: {answer: answer} %>
</div>

app/views/rapidfire/answers/_long.html.erb
<%= render partial: "rapidfire/answers/errors", locals: {answer: answer} %>
<div class="form-group">
<%= f.label :answer_text, answer.question.question_text, class: "title is-6" %>
<%= f.text_area :answer_text, value: answer.answer_text || answer.question.default_text, :rows => 5, placeholder: answer.question.placeholder, class: "textarea" %>
</div>

app/views/rapidfire/answers/_multifile.html.erb
<div>
  <%= f.label :answer_text, answer.question.question_text, class: "block text-sm font-medium leading-6 text-gray-900" %>
  <%= f.file_field :files, multiple: true, class: "block w-full p-1 mt-2 rounded-md border-0 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 sm:text-sm sm:leading-6" %>
  <%= render partial: "rapidfire/answers/errors", locals: {answer: answer} %>
</div>

app/views/rapidfire/answers/_numeric.html.erb
<%= render partial: "rapidfire/answers/errors", locals: {answer: answer} %>
<div class="form-group">
<%= f.label :answer_text, answer.question.question_text, class: "title is-6" %>
<%= f.text_field :answer_text, placeholder: answer.question.placeholder, class: "input" %>
</div>

app/views/rapidfire/answers/_radio.html.erb
<%= render partial: "rapidfire/answers/errors", locals: {answer: answer} %>

<div class="form-group">
  <%= f.label :answer_text, answer.question.question_text, class: "title is-6" %>
  <br>
  <%- answer.question.options.each_with_index do |option, index| %>
    <span class="form-group sub">
      <%= f.label "answer_text_#{index}", class: "radio" do %>
        <%= f.radio_button :answer_text, option, id: "#{f.object_name.gsub(/\]\[|[^-a-zA-Z0-9:.]/, "_").sub(/_$/, "")}_answer_text_#{index}" %>
        <%= option %>
      <% end %>
    </span>
    <br>
  <% end %>
</div>

app/views/rapidfire/answers/_select.html.erb
<%= render partial: "rapidfire/answers/errors", locals: {answer: answer} %>
<% placeholder = answer.question.placeholder.present? ? answer.question.placeholder : "Select your answer" %>
<div class="form-group">
  <%= f.label :answer_text, answer.question.question_text, class: "title is-6" %><br>
  <%= f.select :answer_text, answer.question.options, {include_blank: placeholder}, class: "button is-notification full-width" %>
</div>

app/views/rapidfire/answers/_short.html.erb
<div>
  <%= f.label :answer_text, answer.question.question_text, class: "block text-sm font-medium leading-6 text-gray-900" %>
  <%= f.text_field :answer_text, value: answer.answer_text || answer.question.default_text, placeholder: answer.question.placeholder, class: "block w-full p-1 mt-2 rounded-md border-0 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 sm:text-sm sm:leading-6" %>
  <%= render partial: "rapidfire/answers/errors", locals: {answer: answer} %>
</div>

app/views/rapidfire/attempts/_answer_wrapper.html.erb
<div class='<%= partial -%>_question' >
  <%= render partial: "rapidfire/answers/#{partial}", locals: { f: f, answer: answer } -%>
</div>

app/views/rapidfire/attempts/_form.html.erb
<p class="text-sm p-3 bg-slate-100 rounded-md"><%= @survey.introduction -%></p>

<%= form_for([@survey, @attempt_builder], html: { class: "space-y-3" }, data: { turbo: false } ) do |f| %>
  <%- @attempt_builder.answers.each do |answer| %>
    <%= f.fields_for("#{answer.question.id}", answer) do |answer_form| %>
      <%= render_answer_form_helper(answer, answer_form) %>
    <% end %>
  <% end %>
  <div>
    <%= f.submit submit_text, class: "cursor-pointer rounded-md bg-white px-2.5 py-1.5 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50" %>
  </div>
<% end %>

app/views/rapidfire/attempts/edit.html.erb
<%= render partial: 'form', locals: { submit_text: 'Update' } %>

app/views/rapidfire/attempts/new.html.erb
<div class="flex justify-between items-center">
  <h1 class="font-bold">Taking Survey - <%=@survey.name%></h1>

  <% if can_administer? %>
    <%= link_to "Back to surveys", surveys_path %>
  <% end %>
</div>

<hr class="my-3"/>

<% if @survey.questions.count == 0 %>
  <div class="text-center">
    This Survey does not have any questions yet!
  </div>
<% else %>
  <%= render partial: 'form', locals: { submit_text: "Submit" } %>
<% end %>

app/views/rapidfire/attempts/show.html.erb
<%= @survey.after_survey_content.html_safe %>

app/views/rapidfire/questions/_form.html.erb
<%= form_for form, as: :question, url: url, method: method, html: { class: "grid grid-cols-1 lg:grid-cols-2 gap-6" }, data: { turbo: false } do |f| %>
  <%- if form.errors.any? %>
    <ul class="list-disc list-inside">
      <%- form.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="space-y-3">
    <h4 class="font-semibold underline">Details</h4>
    <div>
      <%= f.label :type, class: "block text-sm font-medium leading-6 text-gray-900" %>
      <%= f.select :type, ::Rapidfire::QuestionForm::QUESTION_TYPES, {include_blank: "Select question Type"}, id: "question_type", class: "block w-full p-1 mt-2 rounded-md border-0 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 sm:text-sm sm:leading-6" %>
    </div>

    <div>
      <%= f.label :question_text, class: "block text-sm font-medium leading-6 text-gray-900" %>
      <%= f.text_field :question_text, class: "block w-full p-1 mt-2 rounded-md border-0 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 sm:text-sm sm:leading-6" %>
    </div>

    <div>
      <%= f.label :position, class: "block text-sm font-medium leading-6 text-gray-900" %>
      <%= f.number_field :position, class: "block w-full p-1 mt-2 rounded-md border-0 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 sm:text-sm sm:leading-6" %>
    </div>

    <div>
      <%= f.label :placeholder, class: "block text-sm font-medium leading-6 text-gray-900" %>
      <%= f.text_field :placeholder, class: "block w-full p-1 mt-2 rounded-md border-0 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 sm:text-sm sm:leading-6" %>
    </div>

    <div>
      <%= f.label :default_text, class: "block text-sm font-medium leading-6 text-gray-900" %>
      <%= f.text_field :default_text, class: "block w-full p-1 mt-2 rounded-md border-0 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 sm:text-sm sm:leading-6" %>
    </div>

    <div>
      <%= f.label :answer_options, class: "block text-sm font-medium leading-6 text-gray-900" %>
      <%= f.text_area :answer_options, rows: 5, class: "block w-full p-1 mt-2 rounded-md border-0 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 sm:text-sm sm:leading-6" %>
    </div>
  </div>

  <div class="space-y-3">
    <h4 class="font-semibold underline">Other options</h4>

    <div>
      <%= f.label :answer_minimum_length, class: "block text-sm font-medium leading-6 text-gray-900" %>
      <%= f.text_field :answer_minimum_length, class: "block w-full p-1 mt-2 rounded-md border-0 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 sm:text-sm sm:leading-6" %>
    </div>

    <div>
      <%= f.label :answer_maximum_length, class: "block text-sm font-medium leading-6 text-gray-900" %>
      <%= f.text_field :answer_maximum_length, class: "block w-full p-1 mt-2 rounded-md border-0 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 sm:text-sm sm:leading-6" %>
    </div>

    <div>
      <%= f.label :answer_greater_than_or_equal_to, class: "block text-sm font-medium leading-6 text-gray-900" %>
      <%= f.text_field :answer_greater_than_or_equal_to, class: "block w-full p-1 mt-2 rounded-md border-0 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 sm:text-sm sm:leading-6" %>
    </div>

    <div>
      <%= f.label :answer_less_than_or_equal_to, class: "block text-sm font-medium leading-6 text-gray-900" %>
      <%= f.text_field :answer_less_than_or_equal_to, class: "block w-full p-1 mt-2 rounded-md border-0 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 sm:text-sm sm:leading-6" %>
    </div>

    <div>
      <%= f.check_box :answer_presence %>
      <%= f.label :answer_presence, class: "ml-1 cursor-pointer inline-block text-sm font-medium leading-6 text-gray-900" %>
    </div>
  </div>

  <div>
    <%= f.submit submit_text, class: "cursor-pointer rounded-md bg-white px-2.5 py-1.5 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50" %>
  </div>
<% end %>

app/views/rapidfire/questions/_question.html.erb
<div class="space-y-2">
  <h4 class="font-medium"><%= question.question_text %></h4>
  <p class="text-xs">
    <%= question.type.split("::").last %> question
  </p>

  <ul class="flex justify-between md:justify-normal md:gap-6 text-sm underline">
    <% if can_administer? %>
      <%= link_to "Edit", [:edit, question.survey, question] %>
      <%= link_to "Delete", [question.survey, question], method: :delete %>
    <% end %>
  </ul>
</div>
<hr class="my-3" />

app/views/rapidfire/questions/edit.html.erb
<div class="container is-fluid full-height">
  <div class="title is-4 notification level">
    <div class="level-left">
      <p class="level-item">
        Edit Question
      </p>
    </div>
    <div class="level-right">
      <div class="level-item">
        <%= link_to "Back to Questions", survey_questions_path(@survey), class: "button" %>
      </div>
    </div>
  </div>
  <%= render partial: 'form', locals: { form: @question_form, url: survey_question_path(@survey, @question), method: :put, submit_text: 'Update Question' } %>
</div>

app/views/rapidfire/questions/index.html.erb
<div class="flex justify-between items-center">
  <h1 class="font-bold"><%= @questions.count %> Question(s)</h1>
  <%= link_to "New Question", new_survey_question_path(@survey) %>
</div>

<hr class="my-3"/>

<% if @questions.count == 0 %>
  <div class="text-center">Please add a few questions.</div>
<% else %>
  <%= render partial: "question", collection: @questions %>
<% end %>

app/views/rapidfire/questions/new.html.erb
<div class="flex justify-between items-center">
  <h1 class="font-bold">Add a question</h1>

  <%= link_to "Back to questions", survey_questions_path(@survey) %>
</div>

<hr class="my-3" />

<%= render partial: 'form', locals: { form: @question_form, url: survey_questions_path(@survey), method: :post, submit_text: 'Create Question' } %>

app/views/rapidfire/surveys/_form.html.erb
<%= form_for survey, html: { class: "space-y-3" }, data: { turbo: false } do |f| %>
  <%- if survey.errors.any? %>
    <ul class="list-disc list-inside">
      <%- survey.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <div>
    <%= f.label :name, class: "block text-sm font-medium leading-6 text-gray-900" %>
    <%= f.text_field :name, class: "block w-full p-1 mt-2 rounded-md border-0 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 sm:text-sm sm:leading-6" %>
  </div>

  <div>
    <%= f.label :introduction, class: "block text-sm font-medium leading-6 text-gray-900" %>
    <%= f.text_area :introduction, rows: 5, class: "block w-full p-1 mt-2 rounded-md border-0 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 sm:text-sm sm:leading-6" %>
  </div>

  <div>
    <%= f.label :after_survey_content, class: "block text-sm font-medium leading-6 text-gray-900" %>
    <%= f.text_area :after_survey_content, rows: 5, class: "block w-full p-1 mt-2 rounded-md border-0 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 sm:text-sm sm:leading-6" %>
  </div>

  <div>
    <%= f.submit "Submit", class: "cursor-pointer rounded-md bg-white px-2.5 py-1.5 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50" %>
  </div>
<% end %>

app/views/rapidfire/surveys/_survey.html.erb
<div class="space-y-3">
  <h4 class="font-medium"><%= survey.name %></h4>
  <p class="text-sm">
    <%= survey.introduction %>
  </p>

  <ul class="flex justify-between md:justify-normal md:gap-6 text-sm underline">
    <% if can_administer? %>
      <%= link_to "Questions", survey_questions_path(survey) %>
      <%= link_to "Results", [:results, survey] %>
      <%= link_to "Delete", survey, method: :delete %>
    <% end %>
    <%= link_to "Attempt", new_survey_attempt_path(survey) %>
  </ul>
</div>
<hr class="my-3" />

app/views/rapidfire/surveys/edit.html.erb
<%= render partial: 'form', locals: {survey: @survey} %>

app/views/rapidfire/surveys/index.html.erb
<div class="flex justify-between items-center">
  <h1 class="font-bold"><%= @surveys.count %> Survey(s)</h1>

  <% if can_administer? %>
    <%= link_to "New Survey", new_survey_path %>
  <% end %>
</div>

<hr class="my-3"/>

<% if @surveys.count == 0 %>
  <% if can_administer? %>
    <div class="text-center">It feels a bit lonely here. Add a new survey to continue.</div>
  <% else %>
    <div class="text-center">All clear here! No suveys available yet.</div>
  <% end %>
<% else %>
  <%= render partial: "survey", collection: @surveys.order(created_at: :desc) %>
  <%= paginate @surveys %>
<% end %>

app/views/rapidfire/surveys/new.html.erb
<div class="flex justify-between items-center">
  <h1 class="font-bold">Add a survey</h1>

  <%= link_to "Back to surveys", surveys_path %>
</div>

<hr class="my-3" />

<%= render partial: 'form', locals: { survey: @survey } %>

app/views/rapidfire/surveys/results.html.erb
<div class="container is-fluid full-height">
  <div class="title is-4 notification level">
    <div class="level-left">
      <p class="level-item">
        Results
      </p>
    </div>
    <div class="level-right">
      <div class="level-item">
        <%= link_to "Back to Surveys", surveys_path, class: "button" %>
      </div>
    </div>
  </div>

  <div class="align-content-center" style="height:25%;margin-left:0.5em">
    <p class="subtitle">
      Page under construction. Results will be available soon!!
    </p>
  </div>
  <hr/>
</div>

<%# <h1>Results</h1> %>

<%# <%- @survey_results.each do |result| %1> %>
<%#   <div> %>
<%#     <h4><%= result.question.question_text %1></h4> %>
<%#     <p> %>
<%#       <%- if result.results.is_a?(Array) %1> %>
<%#         <ol> %>
<%#           <%- result.results.each do |answer| %1> %>
<%#             <li><%= answer %1></li> %>
<%#           <% end %1> %>
<%#         </ol> %>
<%#       <% elsif result.results.is_a?(Hash) %1> %>
<%#         <table> %>
<%#           <thead> %>
<%#             <tr> %>
<%#               <th>Option</th> %>
<%#               <th>Count</th> %>
<%#             </tr> %>
<%#           </thead> %>
<%#           <tbody> %>
<%#             <%- result.results.each do |option, count| %1> %>
<%#               <tr> %>
<%#                 <td><%= option %1></td> %>
<%#                 <td><%= count %1></td> %>
<%#               </tr> %>
<%#             <% end %1> %>
<%#           </tbody> %>
<%#         </table> %>
<%#       <% end %1> %>
<%#   </div> %>
<%# <% end %1> %>